### ISSUE TITLE
Add ability to archive completed tasks to done.txt

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#107]
Add a button (in Settings?) to archive all completed tasks. When tapped, it should download the latest revision of done.txt from Dropbox, and move items marked as done from todo.txt to done.txt, then upload both done.txt and todo.txt.

We can safely assume the user won't perform this action THAT much, which is why I think we should put the button in settings vs on the main screen. I'm open to suggestions re: button placement.

**Comment by andrewheiss** [comment]
Yes! This would be a fantastic new feature. I agree with hiding the button in settings, perhaps as a new one-button section in between the "Todo.txt" and "Dropbox" settings (like the "About" section at the bottom, just up higher on the screen)

**Comment by chuckbjones** [comment]
I'm taking this one.

**Comment by chuckbjones** [comment]
Ok, I've got a working implementation here: https://github.com/chuckbjones/todo.txt-touch-ios/tree/107-archive
It needs more testing and some deodorizing before its ready, though.

What it does:
1. done.txt is synced with Dropbox whenever todo.txt is. The files are only pulled if the revision on dropbox has changed.
2. Archive button has been added to the settings screen. When pressed, archiving is performed and the files are pushed to Dropbox.
3. Auto-archive setting also added to settings screen. Defaults to Off. When on, archiving is performed after a task is completed, before pushing to Dropbox.
4. The archive function appends each completed task from memory is appended to done.txt. todo.txt is then overwritten with all incomplete tasks from memory.
5. done.txt is assumed to be in the same directory as todo.txt

Questions:
1. You can't view/edit archived tasks in the app. Problem?
2. Because of (1), you can't 'undo complete' if auto-archive is enabled.

Other code smells:
- archive has to be called twice (on main screen when you swipe to complete, and on the detail screen when you press the complete button). Not DRY.
- too many calls to reload. Need to make it more efficient (only reload from disk if file has changed)
- pushing done.txt even if it hasn't changed (save lastPushTime and lastPullTime?)
- Need to send done path in pushToRemote (but really shouldn't be sending any paths?)
- if we push todo, then have a conflict pushing done.txt, we're screwed. We should check the rev of each file before uploading either.

**Comment by ginatrapani** [comment]
Fantastic. What it does sounds perfect. I'll begin testing on my devices this weekend.

> 1. You can't view/edit archived tasks in the app. Problem?

No, that's fine for now. Something we might want to do in the distant future.

> 1. Because of (1), you can't 'undo complete' if auto-archive is enabled.

That's fine. If auto-archive is enabled, the completed task is off the todo list anyway, so undo complete isn't an option at all, ie, it doesn't introduce a confusing interface. We'll disable auto-archive by default, so only power completers who want the speed of it will have to turn it on explicitly.

> - archive has to be called twice (on main screen when you swipe to complete, and on the detail screen when you press the complete button). 

But only when auto-archive is on, right? Agree not ideal.

> - pushing done.txt even if it hasn't changed (save lastPushTime and lastPullTime?)

Yeah, this could turn out to be a performance problem. The done.txt file only gets bigger, never gets smaller, so we have to consider performance with a large file, probably up to 1000 lines. (Update: I've been archiving completed items to done.txt since 2007, and my file is 1500 lines right now.)

> - if we push todo, then have a conflict pushing done.txt, we're screwed. We should check the rev of each file before uploading either.

Ah yes, this is a big one. Need to do everything we can to make sure this doesn't happen.

Very happy with the progress here. This makes the app truly standalone.

**Comment by andrewheiss** [comment]
1000 lines might not be enough for a large test case. I've got 1400 lines in my current done.txt file (I should probably clear that out or rename it or something someday), and long time users might be in a similar situation.

**Comment by ginatrapani** [comment]
Running this branch on my devices now. Even with a 1500 line done.txt file, it's quite performant.
