### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by jesusgarza** [todotxt/todo.txt-ios#109]
Unicode support

**Comment by WilliamAlba** [comment]
Not sure if this is related, but when I created a project +$¢ (using the US dollar and cent characters) using my Mac, the Dropbox file will not update properly onto the iPod Touch. Several tasks, both with and without the cent symbol, go missing. The problem goes away when the cent symbol is deleted from the file.

**Comment by WilliamAlba** [comment]
Another observation: although it exists in my todo.txt file, +$ is not available in the project picker.

**Comment by chuckbjones** [comment]
A dollar sign by itself can't be a project or context, because they must end in a 'word' character. From the [Todo.txt Format wiki page](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format):

> A project or context contains any non-whitespace character and must end
> in an alphanumeric or ‘_’. 

I can't reproduce any of the other issues (using the simulator as I don't have a real iOS device handy at the moment). @jesusgarza and @WilliamAlba, are you still having issues. If so, can you provide steps to reproduce the problem or post an example todo.txt that is failing?
