### ISSUE TITLE
Icon badge count doesn't update when Settings are saved

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#129]
In the current state of the project, the app icon's task badge count only updates after you've edited/added/deleted/completed tasks, not when you go into Settings and choose another badge mode.

This bug started happening after @chuckbjones recent changes; I managed to get the badge count setting itself correctly again after task edits in 7c2f1e2677415a7016e91902ae77344e5e7db41a - but I'm not sure how to call updateBadgeCount from the point at which the user changes the setting.

Steps to reproduce:
- Set your badge count to "Priority A tasks"
- Add some A tasks, and some non-A tasks
- Badge looks good. Great.
- Now, go into Settings and set your badge count to "Incomplete Tasks" and tap Done.
- BUG: Go to your homescreen--badge count still is what it was when it was "Priority A tasks"
- Update a task, then check again. Badge count updated.

@paulroub, any chance you have a moment to take a look at this?

**Comment by chuckbjones** [comment]
Yeah, the updateBadge method is called in [taskBag reload], which is called in viewWillAppear. However, I changed  [taskBag reload] so that it only runs if any tasks have changed since last time. 

So, we can either call updateBadge directly from settingsViewControllerDidEnd (we would have to make updateBadge public) or add a 'force' parameter to [taskBag reload] and pass true if the badge setting has changed.

**Comment by ginatrapani** [comment]
Excellent, thanks for the pointer Chuck. Went with adding a force parameter in 0ec3728f2d35cda4582ab138c279caa9543c70e4

**Comment by ginatrapani** [comment]
On second thought, my force implementation didn't check to see if the badge setting changed, so it basically forced every time. Dumb. So I rolled that back and went with making updateBadge public and calling it from settingsViewControllerDidEnd in 45c240503e4f453aab243635e9fa71a89304c050 . Thanks again.
