### ISSUE TITLE
More generic placeholder text for new item

### ISSUE THREAD

**Issue by jgarbers** [todotxt/todo.txt-ios#155]
I'm generally delighted with todo.txt, but I'd like to suggest that the placeholder text that appears whenever a new task is created -- "Call Mom @phone +FamilialPeace" -- be replaced with something more generic. Alternately, the placeholder text could simply stop appearing after the Nth task has been entered.   I'm sure the placeholder is intended to be innocuous and fun, but it may be a rather bitter reminder for users whose moms are no longer with them (especially if she had passed away recently), or whose families have been torn by some strife.  Hope this doesn't come off as over-sensitive, and thanks for your consideration!

**Comment by ginatrapani** [comment]
Acknowledged.  Not over-sensitive at all, in fact I'm disappointed in myself because I lost my Dad at a young age so this should have occurred to me.

Coming up with sample text for the app is a more difficult challenge than you might think, it's why I use fictional character's lists in the app store screenshots. Perhaps we can discuss this on the mailing list with the community?

I'm more comfortable with something off-the-wall/wacky/totally infeasible than something boring, prescriptive, classist.

Think
Set phasers to stun
versus
Pick up golf clubs

The challenge is we need a to-do that has both an obvious project and context in it to demonstrate the usage.

**Comment by jgarbers** [comment]
Thanks for your comments, Gina!  Literary or historical references might work, like:

Return ring to Mt. Doom ASAP @mordor +Fellowship
Take one giant leap for mankind @moon +Apollo

Another possibility -- although it would involve a bit more code -- would be to allow the todo.txt file to contain a line that was marked somehow (# as first character?) as the user's preferred placeholder text.  That way the app could have a fun default, but if somebody wanted something else, perhaps to remind them of their most common contexts, they could just put that in the file.

**Comment by rhussmann** [comment]
Taking ownership of this issue. Proposed (and currently implemented solution):

There is now a placeholders.plist file that contains a list of all placeholders. When the TaskEditView loads, it will randomly choose a placeholder string from placholders.plist.

In the initial commit, I've included all desired sample placeholders mentioned in this thread, and removed the previous default placeholder mentioned in the issue.

Hoping to get my feet wet with ToDo.txt-iOS again, in the absolute non-existent free time I have these days.

**Comment by ginatrapani** [comment]
Ricky! So good to see you! Thanks for this. I'm tied up with Independence Day plans today but I should be able to start reviewing/merging tonight. Very exciting, this app has really fallen behind the Android version.

**Comment by rhussmann** [comment]
No problem, Gina. I didn't expect any immediate action (it's the 4th of July after all!). No rush. I'll be notified whenever you get around to it anyway =o) Hope you're enjoying the nation's birthday!
