### ISSUE TITLE
Update copyright notice in license comments

### ISSUE THREAD

**Issue by rhussmann** [todotxt/todo.txt-ios#166]
I've seen copyright notices of 2011-2012 throughout the application. Shouldn't these be updated to be 2011-2013?

**Comment by ginatrapani** [comment]
Yep, absolutely. I think @brendonjustin has started this in #165.

**Comment by brendonjustin** [comment]
The year(s) in a copyright notice should be the creation year and the most recent year in which a file was modified, like 2009-2011. They should only be changed when the containing file is changed. That is what other projects like VLC and XBMC do.

**Comment by ginatrapani** [comment]
Keeping these dates up-to-date is, frankly, a pain in the rear. We just do a global search and replace at the beginning of a new year for two reasons - it's easier, and git has all the creation/modification dates stored in it, so there's no need to manually maintain that data in the file. (Same reason we don't list author names; they're in the commit log).

**Comment by brendonjustin** [comment]
I see your point, but then why update every file every year? It adds noise to every file's history. As a side effect, it also makes it harder to determine the real copyright year for a particular file.

**Comment by rhussmann** [comment]
To preface this, I am not a lawyer. I did some Googling on updating copyright in source code. Here's a relevant StackExchange thread:
http://programmers.stackexchange.com/a/124692

Relevant snipping:
<snip>
(page 192)

If a date range is used, and not kept up to date has the developer invalidated his/her own copyright beyond the date range?

No, simply the copyright will last from the last recorded date onwards.

</snip>

If this is accurate, and if we are putting copyright in place to protect copyright, then it would make sense to update the copyright on all files, rather than just the last time they were edited. I'm sure there are some nuances here that are beyond my understanding, but with the above information I would be persuaded to update all copyright dates of ToDo.txt owned source code regularly and simultaneously.

Please understand, again, that I am not a lawyer and all above comments are informed by my naive understanding of a thread I found on the internet. Are there any legal folks in our community that could help with advice?

**Comment by brendonjustin** [comment]
I am not a lawyer, but I did pick up a good bit of knowledge on copyright law over the last several years. I'm fairly confident that what I know is correct in the US.

The short version:
- A copyright notice has no legal effect, so changing "(c) 2011-2012" to "(c) 2011-2013" is largely pointless.
- If someone wants to know the date of the most recent change to a file in a git repo, checking its commit history is far and away the most reliable method. Note that changes like "(c) 2011-2012" -> "(c) 2011-2013" are not relevant to copyright duration, so such commits only make it harder to deduce the copyright end date for a file.

The long version:

Putting "(c) abcd-abce" in a work has vanishingly small legal importance. The presence of any copyright notice serves to inform readers that yes, this work is likely protected by copyright law [1]. Someone cannot plausibly claim ignorance that a work is copyrighted, when a prominent notice is present. The notice has no other effect, i.e. it has no legal force.

If someone wants to know with certainty what the effective copyright date is for a file in a git repo, they will look at the timestamp of the most recent relevant-to-copyright commit for the file. Non-code, non-"creative" commits, which are clearly not covered by copyright law, make this more difficult that looking at the most recent commit timestamp in `git log <filename>`. Changing the (c) 2010-2011 to (c) 2010-2013 is an example of a change that would not affect the copyright expiration date of a particular file.

This discussion matters little in the United States. I assume that most code in the project is copyright the respective authors, and thus covered for the life of its author plus 70 years. That effectively means that every file is protected by copyright until 70 years after the last person to make a change dies. The year in which they did so is not a factor. Nothing in this project could possibly lose copyright protection until ~2080, likely long after it becomes irrelevant.

[1] Any work that qualifies for copyright protection, and is not created by the government, is granted copyright protection at creation. Registering with the Copyright Office is unnecessary except to get more money when pursuing claims of copyright infringement. At any rate, "I didn't think it was copyrighted" is entirely implausible since nearly all works from the dawn of software are still protected.

For what it's worth, I don't think anything I wrote disagrees with that SE post.
