### ISSUE TITLE
Enable swipe to delete

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#17]
Should be able to swipe across a todo and get a "Delete" button

**Comment by mcguiresm** [comment]
I'm going to claim this one

**Comment by jperkel** [comment]
Hi, Gina et al.,
If Gina thinks she's an 'iOS noob,' she's got nothing on me. I've been messing around with the code for a while, but still trying to get my feet wet, as it were.

That said, I've figured out how to implement this feature, but don't want to push my code to GitHub, as I'm not sure what else it will break -- I've never worked with a source control system before. 

So how about if I just put the relevant code here? These changes will give you a "swipe to delete" function, except that swiping implements a "complete" button instead (that seems to make more sense to me).

At the moment, this doesn't do anything except produce the button on swiping, because I cannot figure out how to tie it to the task list itself: 

In file: todo_txt_touch_iosViewController.m:

in function - (void) viewDidLoad, add this function call:

```
self.navigationItem.leftBarButtonItem = self.editButtonItem;
```

(This gives you an "edit" button in the toolbar, top left)

Add these 3 functions to the file as well:
- (UITableViewCellEditingStyle) tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath
  {
  return UITableViewCellEditingStyleDelete;
  //    return 3;  // a return value of 3 gives you a red checkmark in a circle like iOS mail
  }
- (void) tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath
  {
  // TODO: Add code to mark task completed.
  }
- (NSString *)tableView:(UITableView *)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)indexPath
  {
  return @"Complete";
  }

Does that help?

**Comment by jperkel** [comment]
@bigbash, I didn't even see you had claimed this already. Feel free to use what I wrote above as a starting point, or start over as you wish. Sorry about that!

**Comment by ginatrapani** [comment]
I'm a big fan of teaching/learning/collaborating in OSS, so you two should totally work together on this. Shawn you can use Jeff's starting code, and maybe show him some git ropes in return. 

At some point it would be really cool for the 3 of us and maybe Chuck to Google Hangout, too. We also have #todotxtapp on freenode.

**Comment by jperkel** [comment]
Thanks Gina, that sounds great to me. Any advice Shawn can offer is much appreciated. Charles Jones has also been quite helpful!

PS -- if you haven't already done so, BTW, upgrade to Xcode 4.2. It has some neat new UI features (eg storyboarding for iOS apps, plus some visual cues tying methods to the app UI) and supports iOS5.

**Comment by mcguiresm** [comment]
I'm no Git guru, truthfully I use Tower Git, unless there are issues then I go back to CLI.  It'd be nice to work on this with @jperkel.  I'm going to add your code tonight to my branch and see about tying in the button with the function.  Are we going to have it then mark the task as completed then?  

I agree with upgrading to Xcode 4.2.  I'm really curious of trying storyboard, I'd like to find a good tutorial on it.  I'd also like to agree with how helpful @chuckbjones is.  I look forward to learning more from everyone, and a G+ hangout would be pretty cool.

**Comment by mcguiresm** [comment]
So I used your code @jperkel with the exception of adding the edit button, it's still not 100% as I'm stuck on getting the view to reload.  I may just be missing something easy due to lack of sleep.  I added `#import "TaskViewController.h"` and the I added: 
`-(void) tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath
{
TaskViewController *completedTask [[TaskViewController alloc] init];
[completedTask didTapCompleteButton];
[competedTask release];
}`

Not really sure this is the best way to do this but I was able to get the swipe gesture to produce the complete button and it runs it but doesn't update the tableView.  If you close the app and then re-open it the task is marked completed.

**Comment by chuckbjones** [comment]
Use `[self reloadData:nil];` to get the screen to update.

Don't instantiate a ViewController just to call a single method on it. Bad side effects may occur. Instead, study what the didTapCompleteButton is doing and re-implement it in the main view controller. You'll probably want to start with something like `Task *task = [tasks objectAtIndex:indexPath.row];`

**Comment by mcguiresm** [comment]
Thanks @chuckbjones!  I wasn't sure if that was a bad idea or not, I'll make the adjustments and test.

**Comment by mcguiresm** [comment]
Ok everything is all done and tested.  Thanks again @chuckbjones for the direction. Pull request submitted.

**Comment by jperkel** [comment]
@bigbash -- glad you were able to get it working. I couldn't figure out how to attach that button to a task action, but I'm glad to see you could!
