### ISSUE TITLE
Bug: When working offline, Upload/download buttons don't do anything

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#76]
To reproduce:
- In settings, turn Work Offline "On"
- Add a new task
- Tap the sync button
- From the prompt, choose "Upload changes". Wait--nothing happens.
- Go back into Settings, and turn Work Offline "Off"
- The Manual sync dialog shows up and you can download/upload.

This is confusing.  We should do 1 of 2 things to make it less confusing:
1. Hide the refresh button entirely while Work Offline is set to on. Alternatively we can make it a "Go Online" button.
2. Make the upload/download buttons actually upload or download while Work Offline is set to On, if the user taps refresh.

**Comment by chuckbjones** [comment]
I'll take this one.

The fact that nothing happens when you press the sync button is also a bug in the Android version ([issue 204](https://github.com/ginatrapani/todo.txt-touch/issues/204)). I implemented it the same way here for parity.

However, we should show the upload/download dialog when offline mode is switched off, so I will implement that now.

**Comment by ginatrapani** [comment]
Hey @chuckbjones, it looks like eda4cc174e51894170d507cd0edb4ef21e77ec41 reintroduced this bug. If you're working offline, the upload/download prompt buttons do nothing; if you come back online, and you tap one of them, they freeze.
